create table app_user (
    id bigint generated by default as identity primary key,
    username varchar(100) not null unique,
    email varchar(255) not null unique,
    password varchar(255) not null,
    refresh_token_hash varchar(255),
    refresh_token_expiry timestamp,
    timezone varchar(100) not null default 'UTC',
    email_reminders_enabled boolean not null default false,
    default_alarm_time time not null default '08:00:00'
);

create table medicine (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    name varchar(255) not null,
    dosage varchar(255) not null,
    frequency varchar(100) not null,
    instructions varchar(2000),
    image_url varchar(1000),
    start_date date not null,
    end_date date,
    constraint fk_medicine_user foreign key (user_id) references app_user(id) on delete cascade
);

create table alarm (
    id bigint generated by default as identity primary key,
    medicine_id bigint not null,
    alarm_time time not null,
    active boolean not null,
    source varchar(20) not null default 'MANUAL',
    constraint fk_alarm_medicine foreign key (medicine_id) references medicine(id) on delete cascade
);

create table alarm_repeat_days (
    alarm_id bigint not null,
    day_name varchar(20) not null,
    primary key (alarm_id, day_name),
    constraint fk_alarm_repeat_days_alarm foreign key (alarm_id) references alarm(id) on delete cascade
);

create table medication_log (
    id bigint generated by default as identity primary key,
    alarm_id bigint not null,
    taken_at timestamp not null,
    status varchar(20) not null,
    constraint fk_medication_log_alarm foreign key (alarm_id) references alarm(id) on delete cascade
);

create table caregiver_relation (
    id bigint generated by default as identity primary key,
    caregiver_id bigint not null,
    patient_id bigint not null,
    constraint fk_caregiver_relation_caregiver foreign key (caregiver_id) references app_user(id) on delete cascade,
    constraint fk_caregiver_relation_patient foreign key (patient_id) references app_user(id) on delete cascade,
    constraint uk_caregiver_patient unique (caregiver_id, patient_id)
);

create index idx_medicine_user_id on medicine(user_id);
create index idx_alarm_medicine_id on alarm(medicine_id);
create index idx_log_alarm_id on medication_log(alarm_id);
create index idx_caregiver_relation_caregiver on caregiver_relation(caregiver_id);
create index idx_caregiver_relation_patient on caregiver_relation(patient_id);
