create table caregiver_access_log (
    id bigint generated by default as identity primary key,
    caregiver_id bigint not null,
    patient_id bigint not null,
    accessed_at timestamp not null,
    constraint fk_caregiver_access_log_caregiver foreign key (caregiver_id) references app_user(id) on delete cascade,
    constraint fk_caregiver_access_log_patient foreign key (patient_id) references app_user(id) on delete cascade
);

create index idx_caregiver_access_log_caregiver on caregiver_access_log(caregiver_id);
create index idx_caregiver_access_log_patient on caregiver_access_log(patient_id);
create index idx_caregiver_access_log_accessed_at on caregiver_access_log(accessed_at);
